name: is_dpelicula
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flip_card: ^0.5.0
  go_router: ^13.2.4
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  flutter_bloc: ^8.1.5
  firebase_core: ^2.29.0
  freezed_annotation: ^2.4.1  # Mantén solo esta entrada
  top_snackbar_flutter: ^3.1.0
  carousel_slider: ^4.2.1
  dio: ^5.4.3
  url_launcher: ^6.2.6
  intl: ^0.19.0
  fpdart: ^1.1.0
  flutter_riverpod: ^2.5.1
  firebase_storage: ^11.7.4
  image_picker: ^1.1.1
  google_maps_flutter: ^2.0.6
  
  google_maps_flutter_web: ^0.3.0
  google_maps: ^6.0.0  # Asegúrate de verificar la última versión disponible
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7  # Asegúrate de que esta versión sea compatible con tu entorno
  freezed: 2.5.2  # Asegúrate de que esta versión sea compatible con tu entorno
  json_serializable: ^6.2.0  # Asegúrate de que esta versión sea compatible con tu entorno
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
