name: is_dpelicula
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flip_card: ^0.7.0
  go_router: ^14.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  flutter_bloc: ^8.1.5
  firebase_storage_web: ^3.0.8
  firebase_core: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  top_snackbar_flutter: ^3.1.0
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.0.0
  dio: ^5.4.3
  uuid: ^4.4.0
  url_launcher: ^6.2.6
  intl: ^0.19.0
  fpdart: ^1.1.0
  file_picker: ^8.0.3
  flutter_riverpod: ^2.5.1
  firebase_storage: ^12.0.0
  image_picker: ^1.1.1
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.5.7
  google_maps: ^7.1.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^2.5.2
  json_serializable: ^6.2.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mision.jpeg
    - assets/foto_sala.jpeg
    - assets/vision.jpeg
    - assets/pareja_m.jpeg
    - assets/historia_m.jpeg
