// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnN84DmiwabIKWHoyImX14ecC1MUPVD_s',
    appId: '1:307076009581:web:6c025d71b1adee2d71f964',
    messagingSenderId: '307076009581',
    projectId: 'dpeliculas-695a1',
    authDomain: 'dpeliculas-695a1.firebaseapp.com',
    databaseURL: 'https://dpeliculas-695a1-default-rtdb.firebaseio.com',
    storageBucket: 'dpeliculas-695a1.appspot.com',
    measurementId: 'G-VBZGBR8CNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeAZxlcFfl_Lb6N8PyT0NNfnjf4KRsy24',
    appId: '1:307076009581:android:2e7c17415d1f802471f964',
    messagingSenderId: '307076009581',
    projectId: 'dpeliculas-695a1',
    databaseURL: 'https://dpeliculas-695a1-default-rtdb.firebaseio.com',
    storageBucket: 'dpeliculas-695a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DUtLn0PclswwyjJZxi8gqS-u3txecpM',
    appId: '1:307076009581:ios:17eadf4f199d0a8971f964',
    messagingSenderId: '307076009581',
    projectId: 'dpeliculas-695a1',
    databaseURL: 'https://dpeliculas-695a1-default-rtdb.firebaseio.com',
    storageBucket: 'dpeliculas-695a1.appspot.com',
    iosBundleId: 'com.example.isDpelicula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DUtLn0PclswwyjJZxi8gqS-u3txecpM',
    appId: '1:307076009581:ios:6968db835b6629ab71f964',
    messagingSenderId: '307076009581',
    projectId: 'dpeliculas-695a1',
    databaseURL: 'https://dpeliculas-695a1-default-rtdb.firebaseio.com',
    storageBucket: 'dpeliculas-695a1.appspot.com',
    iosBundleId: 'com.example.isDpelicula.RunnerTests',
  );
}
